const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_08_04_02_18_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODAsXG4gICAgICAgIDgzLFxuICAgICAgICAxNTUsXG4gICAgICAgIDcxLFxuICAgICAgICAxMzgsXG4gICAgICAgIDk1LFxuICAgICAgICA5MCxcbiAgICAgICAgMTczLFxuICAgICAgICAxNjIsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMTI0LFxuICAgICAgICA2NixcbiAgICAgICAgMjAzLFxuICAgICAgICAxMzksXG4gICAgICAgIDE5NCxcbiAgICAgICAgNDAsXG4gICAgICAgIDQ2LFxuICAgICAgICAxNTcsXG4gICAgICAgIDE4NixcbiAgICAgICAgMjMzLFxuICAgICAgICAxMjgsXG4gICAgICAgIDIzNyxcbiAgICAgICAgMjM5LFxuICAgICAgICA4MCxcbiAgICAgICAgNyxcbiAgICAgICAgMTI0LFxuICAgICAgICAyNDYsXG4gICAgICAgIDQ5LFxuICAgICAgICA4NyxcbiAgICAgICAgMjMzLFxuICAgICAgICA0NSxcbiAgICAgICAgMTA0XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI0MixcbiAgICAgICAgMTkyLFxuICAgICAgICAxNjIsXG4gICAgICAgIDI3LFxuICAgICAgICAxOTEsXG4gICAgICAgIDUwLFxuICAgICAgICAxNTEsXG4gICAgICAgIDg3LFxuICAgICAgICA0MyxcbiAgICAgICAgMjE1LFxuICAgICAgICA4MixcbiAgICAgICAgMTA0LFxuICAgICAgICAxODksXG4gICAgICAgIDEyNyxcbiAgICAgICAgMjM3LFxuICAgICAgICAyMzIsXG4gICAgICAgIDExNixcbiAgICAgICAgMzEsXG4gICAgICAgIDE1NyxcbiAgICAgICAgODEsXG4gICAgICAgIDE4NyxcbiAgICAgICAgNTIsXG4gICAgICAgIDEyMCxcbiAgICAgICAgODEsXG4gICAgICAgIDk3LFxuICAgICAgICAxMTEsXG4gICAgICAgIDEyMixcbiAgICAgICAgMTUyLFxuICAgICAgICAyMzAsXG4gICAgICAgIDEwLFxuICAgICAgICAyMzcsXG4gICAgICAgIDM2XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMjQsXG4gICAgICAgIDE5MyxcbiAgICAgICAgNTYsXG4gICAgICAgIDIxLFxuICAgICAgICAxMzcsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMTEyLFxuICAgICAgICAxMzYsXG4gICAgICAgIDcyLFxuICAgICAgICA4MixcbiAgICAgICAgNzcsXG4gICAgICAgIDQyLFxuICAgICAgICAxNjgsXG4gICAgICAgIDg0LFxuICAgICAgICAxNjEsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMTgwLFxuICAgICAgICAyMCxcbiAgICAgICAgMjIxLFxuICAgICAgICAyOSxcbiAgICAgICAgMTU5LFxuICAgICAgICAxNTAsXG4gICAgICAgIDExMCxcbiAgICAgICAgMTUxLFxuICAgICAgICA3OCxcbiAgICAgICAgMjE1LFxuICAgICAgICA1NCxcbiAgICAgICAgMjIsXG4gICAgICAgIDE3LFxuICAgICAgICAxMjAsXG4gICAgICAgIDIzNSxcbiAgICAgICAgODZcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjQ3LFxuICAgICAgICA4MixcbiAgICAgICAgMTI5LFxuICAgICAgICAyOCxcbiAgICAgICAgMjAzLFxuICAgICAgICA4MSxcbiAgICAgICAgMTQ1LFxuICAgICAgICAxMzksXG4gICAgICAgIDE1MCxcbiAgICAgICAgMjA3LFxuICAgICAgICAwLFxuICAgICAgICAxMzYsXG4gICAgICAgIDE3NCxcbiAgICAgICAgODUsXG4gICAgICAgIDI0NixcbiAgICAgICAgMTI2LFxuICAgICAgICAyNixcbiAgICAgICAgMTcsXG4gICAgICAgIDc3LFxuICAgICAgICAyNDAsXG4gICAgICAgIDEzMyxcbiAgICAgICAgNzEsXG4gICAgICAgIDg4LFxuICAgICAgICAxMzUsXG4gICAgICAgIDMsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMTEzLFxuICAgICAgICA3MSxcbiAgICAgICAgMjU0LFxuICAgICAgICAyMjIsXG4gICAgICAgIDEyNCxcbiAgICAgICAgNzNcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE5MixcbiAgICAgICAgMjQwLFxuICAgICAgICAxMCxcbiAgICAgICAgMTIsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMTg5LFxuICAgICAgICAxMjUsXG4gICAgICAgIDY4LFxuICAgICAgICAxODksXG4gICAgICAgIDE4NixcbiAgICAgICAgMjA3LFxuICAgICAgICAyMTgsXG4gICAgICAgIDEyNyxcbiAgICAgICAgMTA2LFxuICAgICAgICAyMTYsXG4gICAgICAgIDE3NCxcbiAgICAgICAgMTQ0LFxuICAgICAgICAxMDAsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMTAyLFxuICAgICAgICAxMzQsXG4gICAgICAgIDIyMixcbiAgICAgICAgMixcbiAgICAgICAgMTY3LFxuICAgICAgICA5MyxcbiAgICAgICAgNDksXG4gICAgICAgIDIyLFxuICAgICAgICA4NyxcbiAgICAgICAgOTMsXG4gICAgICAgIDIxLFxuICAgICAgICA3OCxcbiAgICAgICAgNzVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjIyLFxuICAgICAgICAxOSxcbiAgICAgICAgMjgsXG4gICAgICAgIDc2LFxuICAgICAgICAyMjAsXG4gICAgICAgIDU3LFxuICAgICAgICA3NyxcbiAgICAgICAgMjA3LFxuICAgICAgICAxNzMsXG4gICAgICAgIDIzNixcbiAgICAgICAgMTcyLFxuICAgICAgICAzLFxuICAgICAgICAyMTMsXG4gICAgICAgIDg1LFxuICAgICAgICAxNTksXG4gICAgICAgIDI2LFxuICAgICAgICAxMzAsXG4gICAgICAgIDE5MSxcbiAgICAgICAgOTAsXG4gICAgICAgIDEyMSxcbiAgICAgICAgMjMwLFxuICAgICAgICA0NixcbiAgICAgICAgMjIwLFxuICAgICAgICAyMDcsXG4gICAgICAgIDEyLFxuICAgICAgICAyMzAsXG4gICAgICAgIDE2MyxcbiAgICAgICAgMTcsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMzEsXG4gICAgICAgIDIzNixcbiAgICAgICAgMTFcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjQ4LFxuICAgICAgICAgIDkyLFxuICAgICAgICAgIDI5LFxuICAgICAgICAgIDcsXG4gICAgICAgICAgMTE0LFxuICAgICAgICAgIDEzMCxcbiAgICAgICAgICAxMzUsXG4gICAgICAgICAgMjA5LFxuICAgICAgICAgIDc5LFxuICAgICAgICAgIDE3NSxcbiAgICAgICAgICAyNDgsXG4gICAgICAgICAgMjI0LFxuICAgICAgICAgIDczLFxuICAgICAgICAgIDQ0LFxuICAgICAgICAgIDYzLFxuICAgICAgICAgIDE3MSxcbiAgICAgICAgICAxMzcsXG4gICAgICAgICAgMTcxLFxuICAgICAgICAgIDE4MyxcbiAgICAgICAgICAxNixcbiAgICAgICAgICA3MixcbiAgICAgICAgICAxMzksXG4gICAgICAgICAgMTgyLFxuICAgICAgICAgIDIsXG4gICAgICAgICAgNTksXG4gICAgICAgICAgMTIwLFxuICAgICAgICAgIDEzOSxcbiAgICAgICAgICAxMjIsXG4gICAgICAgICAgMTA2LFxuICAgICAgICAgIDE1NSxcbiAgICAgICAgICAxNjUsXG4gICAgICAgICAgOTZcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjI2LFxuICAgICAgICAgIDUxLFxuICAgICAgICAgIDUwLFxuICAgICAgICAgIDAsXG4gICAgICAgICAgMTAyLFxuICAgICAgICAgIDQzLFxuICAgICAgICAgIDY3LFxuICAgICAgICAgIDEzMSxcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgMTkwLFxuICAgICAgICAgIDc1LFxuICAgICAgICAgIDE1NyxcbiAgICAgICAgICAyNDcsXG4gICAgICAgICAgMjIzLFxuICAgICAgICAgIDEyOSxcbiAgICAgICAgICAyMjQsXG4gICAgICAgICAgMTk3LFxuICAgICAgICAgIDI0NSxcbiAgICAgICAgICAyMDksXG4gICAgICAgICAgMyxcbiAgICAgICAgICA3NixcbiAgICAgICAgICAyMDQsXG4gICAgICAgICAgMzYsXG4gICAgICAgICAgMTI3LFxuICAgICAgICAgIDIwMCxcbiAgICAgICAgICAxNDAsXG4gICAgICAgICAgMTI4LFxuICAgICAgICAgIDg3LFxuICAgICAgICAgIDE3OCxcbiAgICAgICAgICA2MCxcbiAgICAgICAgICA5MixcbiAgICAgICAgICA5NlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDQyLFxuICAgICAgICAxNTksXG4gICAgICAgIDI0MyxcbiAgICAgICAgMTk1LFxuICAgICAgICAxMzEsXG4gICAgICAgIDYsXG4gICAgICAgIDU4LFxuICAgICAgICAxNTAsXG4gICAgICAgIDI4LFxuICAgICAgICAzNCxcbiAgICAgICAgMTM5LFxuICAgICAgICAxMzQsXG4gICAgICAgIDYwLFxuICAgICAgICAyMTksXG4gICAgICAgIDE3MCxcbiAgICAgICAgMTg4LFxuICAgICAgICA5MSxcbiAgICAgICAgMTk1LFxuICAgICAgICA5LFxuICAgICAgICA3LFxuICAgICAgICAyNTMsXG4gICAgICAgIDI0NCxcbiAgICAgICAgOTAsXG4gICAgICAgIDMyLFxuICAgICAgICAxOCxcbiAgICAgICAgMTg3LFxuICAgICAgICAxNzQsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTc3LFxuICAgICAgICAxNCxcbiAgICAgICAgOTMsXG4gICAgICAgIDM0LFxuICAgICAgICA4OCxcbiAgICAgICAgMTc2LFxuICAgICAgICAyMzMsXG4gICAgICAgIDExLFxuICAgICAgICA2NyxcbiAgICAgICAgMTg0LFxuICAgICAgICAyNDUsXG4gICAgICAgIDIyNSxcbiAgICAgICAgMjM4LFxuICAgICAgICA2OCxcbiAgICAgICAgMjUxLFxuICAgICAgICAxMjQsXG4gICAgICAgIDEsXG4gICAgICAgIDE5NCxcbiAgICAgICAgMTEyLFxuICAgICAgICAxMzMsXG4gICAgICAgIDE4MSxcbiAgICAgICAgOTAsXG4gICAgICAgIDIxMyxcbiAgICAgICAgOTIsXG4gICAgICAgIDIyNixcbiAgICAgICAgMTY2LFxuICAgICAgICAxODcsXG4gICAgICAgIDYxLFxuICAgICAgICAxODQsXG4gICAgICAgIDE4LFxuICAgICAgICAxMzAsXG4gICAgICAgIDc3LFxuICAgICAgICAyNDgsXG4gICAgICAgIDE5LFxuICAgICAgICAzNixcbiAgICAgICAgMFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogODEsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiazMrdzJkVVk3QTZ4TzRrTXZsN1VIUVdaaFlieGVhbUxtS2FuTEt6djVNND1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MjMxOTczODY2MzVAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjYyMUVDOUREREI4NERGMjczMEUxMkE3NjQ3QUM5RDlBXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTczOTg2NTg4NlxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjkyMzE5NzM4NjYzNUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiQzBEOEJFOEVFRjA1M0VBRjY5MDFDRjc1NERFMzZEMkFcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzM5ODY1ODg2XG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMixcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMixcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMSxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcImFLMEdZZVRWUjgyeHhhVHlrLXBUT0FcIixcbiAgXCJwaG9uZUlkXCI6IFwiMWIyOWEzMWEtNjY3NS00NDkzLTk1ZGEtYWNiZDM4YjM3NzMwXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDM5LFxuICAgICAgMjIyLFxuICAgICAgMzksXG4gICAgICAxMzksXG4gICAgICAyNDIsXG4gICAgICA0MixcbiAgICAgIDk1LFxuICAgICAgMTI0LFxuICAgICAgOTQsXG4gICAgICA4NSxcbiAgICAgIDc0LFxuICAgICAgNjYsXG4gICAgICAyMDksXG4gICAgICAxNzEsXG4gICAgICA1MSxcbiAgICAgIDEsXG4gICAgICA2NyxcbiAgICAgIDY5LFxuICAgICAgMTE1LFxuICAgICAgOFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAyMDIsXG4gICAgICAxMDUsXG4gICAgICAxNzYsXG4gICAgICA5OSxcbiAgICAgIDUyLFxuICAgICAgMTYyLFxuICAgICAgNjMsXG4gICAgICA4NSxcbiAgICAgIDExMixcbiAgICAgIDEzMSxcbiAgICAgIDg5LFxuICAgICAgMjMwLFxuICAgICAgMTAxLFxuICAgICAgMTU1LFxuICAgICAgNDksXG4gICAgICAxNyxcbiAgICAgIDE1MCxcbiAgICAgIDI0MCxcbiAgICAgIDY3LFxuICAgICAgMjQ2XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIkYzWFdGUEhMXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCI5MjMxOTczODY2MzU6MThAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjg5NjEwODUxOTg3NjI1OjE4QGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ00yVmdKSUZFSmYrMEwwR0dBTWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiclFRWGd2WWZRdUtqUnVnWmJxZUsxNW1sNTUzeFRJV1hBVWkvcXhnWkdrOD1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCI0S3pIb0JLdkU3OUplQjNLdXRlUWFuTjRZeHdXKzlxd0FCVmdqcTFvYW54eXhITTNNQS9LODB2M0c5K0RDTlV0dG9DNnB0U1U2S01vTFJsOXZUdTlBZz09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJYVUxLVTdOazZIWGpnNThYT2c4SXU0WWhXRDZPNzhzRFZ0ZWRVSi9nMnVSSlllV2hyMFhiV0NXSVo5TmhiT0dZSlV6M2tMN0oveXB4Q3ZuM0RaNllDUT09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI5MjMxOTczODY2MzU6MThAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxNzMsXG4gICAgICAgICAgNCxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAxMzAsXG4gICAgICAgICAgMjQ2LFxuICAgICAgICAgIDMxLFxuICAgICAgICAgIDY2LFxuICAgICAgICAgIDIyNixcbiAgICAgICAgICAxNjMsXG4gICAgICAgICAgNzAsXG4gICAgICAgICAgMjMyLFxuICAgICAgICAgIDI1LFxuICAgICAgICAgIDExMCxcbiAgICAgICAgICAxNjcsXG4gICAgICAgICAgMTM4LFxuICAgICAgICAgIDIxNSxcbiAgICAgICAgICAxNTMsXG4gICAgICAgICAgMTY1LFxuICAgICAgICAgIDIzMSxcbiAgICAgICAgICAxNTcsXG4gICAgICAgICAgMjQxLFxuICAgICAgICAgIDc2LFxuICAgICAgICAgIDEzMyxcbiAgICAgICAgICAxNTEsXG4gICAgICAgICAgMSxcbiAgICAgICAgICA3MixcbiAgICAgICAgICAxOTEsXG4gICAgICAgICAgMTcxLFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDI1LFxuICAgICAgICAgIDI2LFxuICAgICAgICAgIDc5XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3Mzk4NjU4ODQsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFQaWhcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQVBpaC5qc29uIjoge30KfQ==",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
